from __future__ import annotations

from .ui.main_window import (  # noqa: F401
    DEFAULT_ADVANCED_FORM_PROMPT,
    DEFAULT_ADVANCED_HEARING_PROMPT,
    DEFAULT_ADVANCED_MINUTE_PROMPT,
    DEFAULT_CASE_NAME_PROMPT,
    DEFAULT_CLASSIFIER_PROMPT,
    DEFAULT_CLASSIFY_FORM_NAMES_PROMPT,
    DEFAULT_CLASSIFY_HEARING_DATES_PROMPT,
    DEFAULT_CLASSIFY_MINUTE_DATES_PROMPT,
    DEFAULT_CLASSIFY_REPORT_NAMES_PROMPT,
    DEFAULT_SUMMARIZE_HEARINGS_PROMPT,
    DEFAULT_SUMMARIZE_MINUTES_PROMPT,
    DEFAULT_SUMMARIZE_REPORTS_PROMPT,
)

